### ISSUE TITLE
Setting alternative color for icon 

### ISSUE THREAD

**Issue by OscarArango** [cgkineo/adapt-hint#3]
Hello,

Trying to apply an alternative color to both the open and closed state of the icon.  I able to change it for the open state, but the closed state stays black.  Any idea what is the best way to change it?

Update:  Also tried targeting `a ::before` but nothing happens

thanks in advance.

**Comment by tomgreenfield** [comment]
Hi @OscarArango, the selectors below change the icon colours for me in all states:
```less
.hint-extension .hint-extension-button,
.no-touch .hint-extension .hint-extension-button:hover {
	background-color: #ffc200; // amber
	color: #000; // black
}
```
You mention an `<a>` tag which suggests you're on an older version of Hint. I'd advise grabbing a new [download ZIP](https://github.com/cgkineo/adapt-hint/archive/master.zip).
